### ISSUE TITLE
Java does not have verbose error output

### ISSUE THREAD

**Issue by MoogleVII** [stephenhu3/codepal#2]
When trying to run Java code with runtime or compilation errors, the response from HackerEarth only says, 'Syntax Error' without giving a specific line number of cause of compilation or runtime error. This isn't in line with the other languages such as C and Python that HackerEarth supports, which gives a detailed explanation of what went wrong.

**Comment by alec-ng** [comment]
As of 7/11/16, there seems to be verbose error output?
Will need more testing @MoogleVII 

![image](https://cloud.githubusercontent.com/assets/2608077/20084200/9e93f896-a515-11e6-949e-34511ff54a11.png)

**Comment by MoogleVII** [comment]
It seems to be that you need to have at the very minimum a class declaration and a main function within the class. if those are not present then you get "fix the syntax errors" otherwise it will give verbose output
