### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by alec-ng** [stephenhu3/codepal#31]
Remove divider
![image](https://cloud.githubusercontent.com/assets/2608077/20084416/fddfcce8-a516-11e6-9f0b-c27c48a39833.png)

Style y-overflow
![image](https://cloud.githubusercontent.com/assets/2608077/20084423/0ec57832-a517-11e6-89b5-9104a55b3081.png)

Style output
![image](https://cloud.githubusercontent.com/assets/2608077/20084424/167261d0-a517-11e6-9b48-2ff845daad73.png)

Style tabs
![image](https://cloud.githubusercontent.com/assets/2608077/20084431/21d55cd0-a517-11e6-9c90-6c710738c39d.png)

**Comment by MoogleVII** [comment]
Grey divider has been removed as of goldenlayout integration
