### ISSUE TITLE
incorrectly fetching files

### ISSUE THREAD

**Issue by gaviral** [stephenhu3/codepal#36]
![image](https://cloud.githubusercontent.com/assets/12901566/20151666/d7c3ee5e-a66f-11e6-9ca1-c1b4b905e3d5.png)

**Comment by alec-ng** [comment]
@AviralGarg1993 Can you include more information... what were you trying to accomplish? What was trying to fetch the file? What are the files for? Steps to reproduce?

**Comment by gaviral** [comment]
I shall do that later today.
