### ISSUE TITLE
No functionality for the Back button in stackOverflow yet.

### ISSUE THREAD

**Issue by tkalra** [stephenhu3/codepal#38]
The back button in the goldenlayout window does not contain the functionality that allows it to return to the last search query. 
Steps to reproduce-
1) Search query: " pointer in c++"
2) replace the search query by : " abstract classes"
3) Click back. Should take you back to "pointer in c++ results " but doesnot.

![capture](https://cloud.githubusercontent.com/assets/9021023/20194488/64a41f7e-a747-11e6-8887-d253c06bebf9.PNG)

**Comment by anhduc130** [comment]
Fixed!
