### ISSUE TITLE
HackerEarth CORS Issue

### ISSUE THREAD

**Issue by alec-ng** [stephenhu3/codepal#40]
The following occurs when trying to press "Run" for the CodeEditor module:

![image](https://cloud.githubusercontent.com/assets/2608077/20163903/1ad82706-a6b5-11e6-95a9-3c62a44395aa.png)

This issue was circumvented by using the Allow Control Allow Origin plugin for Chrome (https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en), but enabling this plugin will block YouTube from working.

The following host was registered in the api:

![image](https://cloud.githubusercontent.com/assets/2608077/20163937/62c66118-a6b5-11e6-8d22-a8ecfda70a8e.png)

And the error occurs when running on (http://stephenhu.me/codepal/main.html).

**Comment by alec-ng** [comment]
Checked that the client secret key matches. One potential issue might be how the domain is being redirected from GitHub pages. @stephenhu3 any insight, since stephenhu3.github.io redirects to stephenhu.me?
Emailed HackerEarth support to see what their thoughts are.

**Comment by stephenhu3** [comment]
It could be. I've mentioned to Aviral and Andrew too, but branching and deploying to your own github domain might be worth a shot for debugging. Then, the URL will be https://username.github.io

Not sure if HackerEarth requires it, but HTTPS is provided on the gh-pages URL too.

There's an account-wide setting for my github account that routes all traffic to the domain I purchased which hosts my personal portfolio. I was planning to deploy this project on a separate github account with a common "codepal-site" username.

**Comment by alec-ng** [comment]
HackerEarth has been replaced with repl.it.
