### ISSUE TITLE
Code Editor occasionally does not initialize correctly on first open

### ISSUE THREAD

**Issue by MoogleVII** [stephenhu3/codepal#43]
Sometimes when opening codepal.ca the code editor module does not initialize correctly, creating no tab or text editing area. This seems to (for me) always occur on the first time opening the webpage. Upon refresh it works fine from that point on.
![editoriniterror](https://cloud.githubusercontent.com/assets/22357053/20324289/d8caed9c-ab34-11e6-902b-3ce20f47b3e9.png)

**Comment by alec-ng** [comment]
https://github.com/stephenhu3/codepal/commit/88ab807135f57a2d34eb7a0653493d654614b90b

Changed the way JavaScript is initialized.
