### ISSUE TITLE
stackOverflow upgrade needed

### ISSUE THREAD

**Issue by gaviral** [stephenhu3/codepal#64]
stackOverflow component needs to show content in the component itself instead of redirecting it to a new tab and the list of questions also needs to look better

![image](https://cloud.githubusercontent.com/assets/12901566/20523672/096c2c1e-b06b-11e6-8729-8fa87e61f435.png)

**Comment by MoogleVII** [comment]
Has this been resolved? @AviralGarg1993

**Comment by gaviral** [comment]
Andrew has made some progress and is working on some UI bugs. @anhduc130 any updates on this?

**Comment by anhduc130** [comment]
Yes! We got it worked!
