### ISSUE TITLE
repl object is not re-created upon switching tabs

### ISSUE THREAD

**Issue by MoogleVII** [stephenhu3/codepal#67]
When switching between tabs that are using different languages, the repl object/client is not re-instantiated with the switched-to tab's language, causing compile errors (the repl API is evaluating the code in the wrong language)

**Comment by alec-ng** [comment]
Fixed - https://github.com/stephenhu3/codepal/commit/1a395eb629c5cfbf3765387e3ae6a3bd47f37b8c
