### ISSUE TITLE
Resize Code Editor when golden layout container height changes

### ISSUE THREAD

**Issue by alec-ng** [stephenhu3/codepal#72]
![image](https://cloud.githubusercontent.com/assets/2608077/20637993/7649abec-b34d-11e6-97ff-4d6fee38c3e4.png)

Changing the width of the golden layout container encapsulating the code editor doesn't make the editor resize vertically.

I recall seeing a resize() function the ace editor API has to manually resize..

**Comment by MoogleVII** [comment]
Implemented in recent commit
