### ISSUE TITLE
Home page doesn't redirect to main upon successful login

### ISSUE THREAD

**Issue by alec-ng** [stephenhu3/codepal#86]
Expected behaviour: If there is an existing facebook session, going to codepal.ca automatically takes you to codepal.ca/main.html

Actual behaviour: you stay on codepal.ca

Expected behaviour: on the login page, after a successful facebook login, the site redirects you to codepal.ca/main.html

Actual behaviour: you stay on codepal.ca

**Comment by anhduc130** [comment]
Fixed!
